engines:
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
exclude_paths:
- node_modules
- data
- spec/lib/
- src/main.js
- spec/test.js
- gulpfile.js
