engines:
  eslint:
    enabled: true
    config: ./eslintrc.js
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_paths:
- node_modules
- spec/lib/
- src/main.js
- spec/test.js
- gulpfile.js
