engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_paths:
- node_modules
- data
- spec/lib/
- src/main.js
- spec/test.js
