language: node_js
node_js:
    - "node"
script: gulp test
before_script:
  - npm install
  - npm install gulp
after_script:
  - istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
