language: node_js
node_js:
    - "node"
script: gulp test
before_script:
  - npm install
  - npm install gulp
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
    code_climate:
        repo_token: 22eb8a4fb781ca8bfc39ca8ec53a91b7e5940dff30315ae5ed415aab4329b379
